server.port=8888

spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations[0]=classpath:config/telemetry/{application}

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/