spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

kafka.topic.telemetry.sensors-topic=telemetry.sensors.v1
kafka.topic.telemetry.hubs-topic=telemetry.hubs.v1

logging.level.ru.yandex.practicum=TRACE
grpc.server.port=59091