spring.application.name=collector
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.config.import=optional:configserver:
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

spring.producer.bootstrap-servers=localhost:9092
spring.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

kafka.topic.telemetry.hubs-topic=telemetry.hubs.v1
kafka.topic.telemetry.snapshots-topic=telemetry.snapshots.v1

topic.telemetry-sensors=telemetry.sensors.v1

logging.level.ru.yandex.practicum=TRACE
grpc.server.port=59091
server.port=8085