spring.config.import=optional:configserver:

spring.cloud.compatibility-verifier.enabled=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

kafka.topic.telemetry.sensors-topic=telemetry.sensors.v1
kafka.topic.telemetry.hubs-topic=telemetry.hubs.v1

logging.level.ru.yandex.practicum=TRACE
grpc.server.port=${GRPC_SERVER_PORT:${COLLECTOR_PORT:59091}}

spring.cloud.config.fail-fast=false
spring.cloud.config.enabled=false

eureka.client.enabled=false